### ISSUE TITLE
Dyskusja z Facebooka

### ISSUE THREAD

**Issue by gknor** [ksopyla/awesome-nlp-polish#2]
Spójrz proszę na tą dyskusję:
https://m.facebook.com/groups/971898396201529?view=permalink&id=2791223434269007
Może być pomocna.
Pozdrawiam

**Comment by ksopyla** [comment]
Dzięki, okres świąteczny mnie wyłączył z aktywności. Dopiero dziś nadrabiam.

**Comment by ksopyla** [comment]
Widziałem i większość rzeczy znajduje się na liście
